# Generated by Django 4.0.4 on 2022-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogroopa', '0007_comment_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
