# Generated by Django 4.0.4 on 2022-06-17 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
