# Generated by Django 4.0.4 on 2022-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0007_topic_alter_post_author_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='blog1_posts', to='blog1.topic'),
        ),
    ]
